version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-local-aws
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=teste
      - AWS_SECRET_ACCESS_KEY=teste
      - EDGE_PORT=4566
      - DATA_DIR=${DATA_DIR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      #- services=s3,dynamoDB
      #- DEBUG=1
      #- ENDPOINT_URL=http://localhost:4566
    ports:
      - '4566-4587:4566-4587'
    #profiles:
      #- acesso_cli
    volumes:
      #- "./.localstack:/var/lib/localstack"
      #- localstack-data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - dev_to

volumes:
  localstack-data:
    name: localstack-data

networks:
  dev_to:
    name: dev_to